env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-MUL-200-COT-2-1-mypaint-mariane.sedjro.git"
  EXECUTABLES: my_paint

name: chocolatines

on:
  push:
    branches:
      - main

jobs:

  check_coding_style:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/epitech/coding-style-checker:latest

    steps:
      - name:   run coding style checker
        uses:   actions/checkout@v3
      - name:   check script
        run:    check.sh $(pwd) $(pwd)

